// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnbicmkodbykqjtiigvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuYmljbWtvZGJ5a3FqdGlpZ3ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MTczNjgsImV4cCI6MjA3MjI5MzM2OH0.sPDPr5zUPrza0u6sareEpYlN322l45BsiPsOH1NEILg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});